apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    build.appstudio.openshift.io/application: appstudio
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: devfile-sample-go-basic
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-go-basic
  namespace: gbenhaim-app
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_gbenhaim_devfile-sample-go-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/gbenhaim/devfile-sample-go-basic.git
